### ISSUE TITLE
找不到指定版本的ayaka

### ISSUE THREAD

**Issue by duoshoumiao** [bridgeL/criminal_dance#1]
找不到指定版本的ayaka

**Comment by bridgeL** [comment]
给个报错截图看看

**Comment by duoshoumiao** [comment]
> 给个报错截图看看

![VH3%SO)RGCJT`8MQKD487N8](https://user-images.githubusercontent.com/94856184/217710321-51db22b7-ec3e-48d8-84db-43467425555e.png)

**Comment by bridgeL** [comment]
![image](https://user-images.githubusercontent.com/47290820/217710723-42a332d7-733a-4078-abed-648fc727a426.png)

**Comment by duoshoumiao** [comment]
> ![图像](https://user-images.githubusercontent.com/47290820/217710723-42a332d7-733a-4078-abed-648fc727a426.png)

还是安装不了

**Comment by bridgeL** [comment]
> > ![图像](https://user-images.githubusercontent.com/47290820/217710723-42a332d7-733a-4078-abed-648fc727a426.png)
> 
> 还是安装不了

没有报错截图，我就什么判断都做不了

**Comment by duoshoumiao** [comment]
> > > ![图像](https://user-images.githubusercontent.com/47290820/217710723-42a332d7-733a-4078-abed-648fc727a426.png)
> > 
> > 
> > 还是安装不了
> 
> 没有报错截图，我就什么判断都做不了

 我装的是3.10.7的 也是报图片那个问题。

**Comment by bridgeL** [comment]
算卦：

卦象其一：环境变量错误
1. 检查pip版本 `pip -V`，是否与python3.10相配，检查python版本，是否真的是3.10，`python -V`
2. 若错误，自行搜索环境变量问题如何解决

卦象其二：使用了虚拟环境poetry
1. 请修改poetry当前的python环境为3.10
2. 在poetry shell 中 pip install ayaka

卦象其三：总之就是不能用
1. 建议直接克隆本仓库和[ayaka](https://github.com/bridgeL/ayaka)仓库
2. 将本仓库中的criminal_dance文件夹和ayaka仓库中的ayaka文件夹放到你的机器人目录下
3. 曲线救国
