### ISSUE TITLE
Bug: No module named 'criminal_dance'

### ISSUE THREAD

**Issue by yuyue31** [bridgeL/criminal_dance#2]
描述你的问题
ERROR: Failed to import and load "hoshino.modules.criminal_dance.run", error: No module named 'criminal_dance'
ERROR: No module named 'criminal_dance'
- 你做了什么，我正常加载了插件，显示以上报错
- 本应该如何，应该正常运行
- 但是却报错

提供以下必要信息

- 你使用的是什么机器人框架？hoshino
- criminal_dance的版本    最新的
- 报错截图（尽量完整，至少保证最后10行被截到）
![A_}S9FDM7LCMXCJ{HZSBF3U](https://user-images.githubusercontent.com/106214532/224218989-b38bbe27-9976-4979-a170-56cac93e6ee6.png)
![TI{1KJQT2OZGHJ@4{}ZWK%A](https://user-images.githubusercontent.com/106214532/224219080-dbb507d2-8222-4126-812b-9a32fc9a0d7f.png)

**Comment by bridgeL** [comment]
我之前没怎么用hoshino，所以设计插件时，其安装方式和hoshino其他插件的常用方式有一些不同

1. 我推测你是直接在module文件夹下`git clone`了本仓库，我猜测你当前的文件目录是这样的

```
module
	criminal_dance（外部的）
		criminal_dance（内部的）
			cards
			__init__.py
			...
		run.py以及其他文件...
```

但是这并不能正常，应当改成如下

```
module
	criminal_dance（内部的）
		cards
		__init__.py
		...
```

**删除run.py以及其他文件**，同时仅使用内部的那个criminal_dance文件夹

2. 此外，你还需要**升级依赖，`pip install ayaka -U`**，ayaka的版本至少为0.0.4.x才能让当前版本的criminal dance正常工作

3. by the way，如果**仍然存在问题**，请提供**新的报错截图**以及更多信息：

- 你是否使用了虚拟环境，venv / poetry / pdm ？
- 你是否使用了其他依赖于ayaka的插件，例如：ayaka_games？
